# Generated by Django 4.2.8 on 2025-12-31 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=255, unique=True)),
                ('request_count', models.BigIntegerField(default=0)),
                ('blocked_count', models.BigIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Domain stats',
                'ordering': ['-request_count'],
            },
        ),
        migrations.CreateModel(
            name='IPHostnameCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('operator', 'Operator'), ('admin', 'Administrator')], default='viewer', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('response_time', models.IntegerField(default=0, help_text='Response time in milliseconds')),
                ('method', models.CharField(default='GET', max_length=10)),
                ('url', models.TextField(blank=True, default='')),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('status_code', models.IntegerField(default=0)),
                ('source_ip', models.GenericIPAddressField(db_index=True)),
                ('source_port', models.IntegerField(default=0)),
                ('destination_ip', models.CharField(default='0.0.0.0', max_length=45)),
                ('destination_port', models.IntegerField(default=0)),
                ('content_length', models.BigIntegerField(default=0)),
                ('blocked', models.BooleanField(db_index=True, default=False)),
                ('block_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('block_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'blocked'], name='dashboard_p_timesta_534cf2_idx'), models.Index(fields=['hostname', '-timestamp'], name='dashboard_p_hostnam_28b772_idx'), models.Index(fields=['source_ip', '-timestamp'], name='dashboard_p_source__af910d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('block', 'Block'), ('unblock', 'Unblock')], max_length=20)),
                ('target_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_id', models.CharField(blank=True, max_length=100, null=True)),
                ('target_name', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
