# Generated by Django 4.2.8 on 2025-12-29 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('manual', 'Manual'), ('ads', 'Advertising'), ('malware', 'Malware'), ('phishing', 'Phishing'), ('adult', 'Adult Content'), ('social', 'Social Media'), ('gambling', 'Gambling'), ('streaming', 'Streaming'), ('gaming', 'Gaming'), ('other', 'Other')], default='manual', max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_wildcard', models.BooleanField(db_index=True, default=False)),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blocked Domain',
                'verbose_name_plural': 'Blocked Domains',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=45)),
                ('ip_type', models.CharField(choices=[('source', 'Source IP'), ('destination', 'Destination IP'), ('both', 'Both')], default='source', max_length=20)),
                ('is_range', models.BooleanField(default=False)),
                ('cidr_prefix', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(db_index=True)),
                ('port_end', models.IntegerField(blank=True, null=True)),
                ('port_type', models.CharField(choices=[('source', 'Source Port'), ('destination', 'Destination Port'), ('both', 'Both')], default='destination', max_length=20)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('both', 'Both')], default='tcp', max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blocked Port',
                'verbose_name_plural': 'Blocked Ports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain_pattern', models.CharField(blank=True, max_length=255, null=True)),
                ('source_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('source_ip_cidr', models.IntegerField(blank=True, null=True)),
                ('dest_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('dest_ip_cidr', models.IntegerField(blank=True, null=True)),
                ('source_port_start', models.IntegerField(blank=True, null=True)),
                ('source_port_end', models.IntegerField(blank=True, null=True)),
                ('dest_port_start', models.IntegerField(blank=True, null=True)),
                ('dest_port_end', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=100)),
                ('action', models.CharField(choices=[('block', 'Block'), ('allow', 'Allow'), ('log', 'Log Only')], default='block', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Block Rule',
                'verbose_name_plural': 'Block Rules',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
